// src/layouts/RootLayout.tsx
import React from "react";
import "../globals.css"; // adapte le chemin selon ton projet

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="fr">
      <head>
        <title>Readdy Site</title>
        <meta name="description" content="Generated by Readdy" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Polices Google pour Pacifico, Geist */}
        <link
          href="https://fonts.googleapis.com/css2?family=Pacifico&family=Geist&family=Geist+Mono&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
